- block:

  - name: set user.name
    git_config: name=user.name scope=global value="{{ name }}"
    sudo: no

  - name: set user.email
    git_config: name=user.email scope=global value="{{ email }}"
    sudo: no

  tags:
    - git
