- block:

#  - name: yum update
#    yum:
#      name: '*'
#      state: latest
#
  - name: yum package install
    yum:
      name: "{{ item.name }}"
      state: "{{ item.state | default('present') }}"
    with_items: "{{ packages }}"

  tags:
    - yum
